            - name: coverage.py badge
  # You may pin to the exact commit or the version.
  # uses: tj-actions/coverage-badge-py@782bdaaa8b2e37612e6b6fac5e559e5544e6eef2
  uses: tj-actions/coverage-badge-py@v2.0.3
  with:
    # Output path to write the coverage badge.
    output: # optional, default is coverage.svg
    # Overwrite an existing coverage badge.
    overwrite: # optional, default is true
    # Current working directory
    working-directory: # optional, default is .
          
